#!/bin/bash

if [[ -z "$1" ]]; then
  echo "You must pass a file argument to this script!"
  exit 1
fi

filePath="$PWD/$1"

if [[ -f "$filePath" ]]; then
  outputFilePath="$PWD/`basename $filePath .c`"
  gcc -ggdb -o "$outputFilePath" "$filePath"
  $outputFilePath <&0
  if [ "$?" != '0' ];then
    gdb "$outputFilePath"
  fi
  rm "$outputFilePath"
else
  echo "The following file does not exist: $file"
  exit 1
fi
